openapi: 3.0.0
info:
  title: Bill Aggregation Service API
  version: 1.0.0
  description: API for managing utility bills and accounts

servers:
  - url: http://localhost:8081
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time

    Bill:
      type: object
      properties:
        id:
          type: string
        linked_account_id:
          type: string
        provider_id:
          type: string
        amount:
          type: number
        due_date:
          type: string
          format: date-time
        status:
          type: string
          enum: [paid, unpaid, overdue]
        bill_date:
          type: string
          format: date-time

    BillSummary:
      type: object
      properties:
        bill_count:
          type: integer
        bills:
          type: array
          items:
            $ref: '#/components/schemas/Bill'
        total_due:
          type: number

paths:
  /accounts/link:
    post:
      summary: Link a utility account
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                provider_id:
                  type: string
                credentials:
                  type: string
      responses:
        '200':
          description: Account linked successfully
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /bills:
    get:
      summary: Get all bills for a user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of bills
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillSummary'
        '401':
          description: Unauthorized

  /bills/refresh:
    post:
      summary: Refresh bills for a user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Bills refreshed successfully
        '401':
          description: Unauthorized

  /accounts/{account_id}:
    delete:
      summary: Delete a linked account
      security:
        - BearerAuth: []
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Account not found 